### ISSUE TITLE
Command issue

### ISSUE THREAD

**Issue by WordStormRose** [YUNG-GANG/YUNGs-Better-Strongholds#12]
The /locate stronghold command in the most recent forge 1.16 version isn't working; it just says "Could not find that structure nearby". I am using Oh The Biomes You Go, Atmospheric, and Better Default Biomes along with your caves and mineshaft mods.

**Comment by yungnickyoung** [comment]
Use `/locate betterstrongholds:stronghold`

**Comment by WordStormRose** [comment]
Thank you!

**Comment by yungnickyoung** [comment]
Lol you got it! (Don't worry about the message before, I just thought it was funny)
