### ISSUE TITLE
what is forge-6/forge-3/forge-4

### ISSUE THREAD

**Issue by Lupetto09** [YUNG-GANG/YUNGs-Better-Strongholds#14]
please what and where can I download it?

**Comment by TelepathicGrunt** [comment]
can you go into more detail of what you mean by forge-6/forge-3/forge-4? Where do you see that?

**Comment by Lupetto09** [comment]
when I start the game I see this mod requires 1.16.5 forge-6

**Comment by TelepathicGrunt** [comment]
You can download 1.16.5 forge from here. https://files.minecraftforge.net/net/minecraftforge/forge/ 
Grab 1.16.5 - 36.1.16 Forge, install it, and launch the game with the new forge profile

**Comment by Lupetto09** [comment]
That's the first thing I doed before calling for support

**Comment by Lupetto09** [comment]
sorry I found the error and resolved it, thank you for the help
