### ISSUE TITLE
Stronghold not spawning with Lost Cities installed

### ISSUE THREAD

**Issue by Jashith127** [YUNG-GANG/YUNGs-Better-Strongholds#15]

**Comment by yungnickyoung** [comment]
Please provide more info or ask for help on Discord.

**Comment by Gregor7008** [comment]
I've got the same problem. When I type in /locate betterstrongholds:stronghold it doesnt find anything...

Edit: Well, never mind, I found the problem I think: When you've got The Lost Cities installed, the stronghold will, for some reason, not generate. I took out this mod, created a new world and here I am: I've got a stronghold

**Comment by AtlasRiker** [comment]
Can confirm, seems to be an incompatibility with the lost cities mod.

**Comment by yungnickyoung** [comment]
Well, that's an unexpected problem. Please try making an issue report with the folks over at Lost Cities and see if they know anything about this.

**Comment by TelepathicGrunt** [comment]
Whitelist the Lost Cities dimension in Better Stronghold's config everyone to get the stronghold to spawn in the Overworld. It's a bit complicated to explain but has to do with Lost Cities using the overworld's noise setting which is perfectly fine for them to do.

**Comment by yungnickyoung** [comment]
Solution is posted above.
