### ISSUE TITLE
Mod does not work with Gobber 

### ISSUE THREAD

**Issue by NICDP123** [YUNG-GANG/YUNGs-Better-Strongholds#16]
Hello yungnickyoung,

I tried your mod named "BetterStrongholds-Fabric-1.16.5-1.0" 
and when I type in /locate betterstrongholds:stronghold (in a new generated world)
the game can find your stronghold
and with a mod named "Gobber [FABRIC]" (version 1.16.5-2.3.71) by kwpugh added
the game says "Could not find that structure nearby" preventing the command to give coordinate of the stronghold
(maybe it also does not generate your stronghold when creating a new world ?).

Gobber mod by kwpugh:
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric/files/3232918

My Fabric Version:
Fabric Version: 1.16.4
Fabric Loader: 0.11.3

**Comment by TelepathicGrunt** [comment]
Whitelist the two Gobber dimensions in Better Stronghold's config to get the stronghold to spawn in the Overworld. It's a bit complicated to explain but has to do with Gobber's dimensions using the overworld's noise setting which is perfectly fine for them to do.

**Comment by NICDP123** [comment]
It worked, thank you so much!

**Comment by NebelNidas** [comment]
Can't these dimensions be whitelisted by default then? Or at least add a notice to the CurseForge page. Because I've been wasting the last two hours trying to figure out why no strongholds generate 😅

**Comment by TelepathicGrunt** [comment]
@NebelNidas the better thing would be for fabric to port my forge pr into fabric API https://github.com/MinecraftForge/MinecraftForge/pull/7777

But I dont know if that'll happen even though my fix would solve this issue entirely

**Comment by yungnickyoung** [comment]
I've added a notice to the CurseForge pages.
