### ISSUE TITLE
Quark caves can destroy Better Strongholds

### ISSUE THREAD

**Issue by niraqw** [YUNG-GANG/YUNGs-Better-Strongholds#17]
Quark's cave generation can destroy large sections of Better Strongholds, including the portal room.

Screenshot taken at 1560 31 -1278 on seed "-5544598888101810961".
![2021-05-19_19 09 52](https://user-images.githubusercontent.com/22210045/118910213-f94dbc00-b8d8-11eb-8c00-ef2c0ed41fba.png)

Minecraft 1.16.5
Forge 36.1.16
Mods: 
AutoRegLib 1.6-47
BetterStrongholds v1.1
Quark r2.4-311
YUNG's API vForge-6

**Comment by yungnickyoung** [comment]
This is an issue on Quark's end that I cannot fix.
