### ISSUE TITLE
No end portal

### ISSUE THREAD

**Issue by gravsfx** [YUNG-GANG/YUNGs-Better-Strongholds#18]
I am using all the other YUNG mods like better caves, better mineshafts and all that stuff. I noticed that both better mineshafts and better caves have permission over the stronghold to generate through it effectively replacing the end room with a mineshaft or cave. Is there a way to give the stronghold first say in where it spawns so nothing breaks it?

**Comment by yungnickyoung** [comment]
Neither the caves nor mineshaft will do this. The only exception is a bug where the mineshaft's supports that generate below the main tunnel will replace air within the stronghold, but only air and nothing else. It's not possible for the end portal to be affected.

If you have an end portal being affected by cave gen, it is likely a Quark crevice or mega cave.

**Comment by gravsfx** [comment]
Quark crevices was the issue! Thanks
