### ISSUE TITLE
[1.16.5] Advancement Eye Spy not triggering when entering the stronghold. 

### ISSUE THREAD

**Issue by Gbergz** [YUNG-GANG/YUNGs-Better-Strongholds#2]
Title ^

Tested on an instance with just YUNGs-Better-Strongholds & YUNGs API nothing else.

**Minecraft**: 1.16.5
**Forge**: 36.1.2
**Betterstrongholds**: 1.0.1

**Comment by yungnickyoung** [comment]
Gotcha, I'll add a trigger for the achievement soon

**Comment by yungnickyoung** [comment]
Just an update - I tried to get this working, but for some reason I couldn't get it to properly override the vanilla advancement. I'll revisit it in the future and hopefully get it working then.

**Comment by Gbergz** [comment]
Glad to hear you've tried to fix it. Looking forward to it working in the future, maybe you could add a seperate advancement for your structure. 

It's just that I have a quest to enter the stronghold in my modpack and adding this would break it.

**Comment by yungnickyoung** [comment]
Added in the latest versions for Forge/Fabric 1.16. 1.17 will get it soon :)

**Comment by yungnickyoung** [comment]
Added to all versions!
