### ISSUE TITLE
Doesn't work sometimes

### ISSUE THREAD

**Issue by ZephaniahNoah** [YUNG-GANG/YUNGs-Better-Strongholds#20]
Better strongholds don't generate sometimes. There was a frozen river nearby so I removed that biome from the blacklist and recreated the world. Still didn't generate a better stronghold. No oceans nearby. Is this a mod compatibility issue? I'll leave a list of all my mods and their versions.
![2021-06-06_20 19 54](https://user-images.githubusercontent.com/14168013/120968552-b8410e80-c704-11eb-84d8-54921ea14521.png)
Seed: -4640855178592038691
Mods:
Abnormals Core: 3.1.1
Auto Reg Lib: 1.6-49
Bayou Blues: 1.0.4
YUNGS Better Caves: 1.1.2
YUNGS Better Mineshafts: 2.0.3
YUNGS Better Strongholds: 1.1
Oh The Biomes You'll Go: 1.2.9
BYG Enhanced Trees: 1.0
Dungeon Crawl: 2.2.4
Optifine: G8
Quark: r2.4-312
Subterranean Wilderness: 1.2.1
TerraForged: 0.2.10
YUNGS API: 6

**Comment by yungnickyoung** [comment]
Can you pastebin a latest.log when running your modpack?

**Comment by ZephaniahNoah** [comment]
[latest.log](https://github.com/user-attachments/files/22181859/latest.log)

**Comment by yungnickyoung** [comment]
Have you tried in a brand new world? And if it's a Terraforged world - when creating the world, double check in the Terraforged settings that Better Strongholds are listed.

**Comment by ZephaniahNoah** [comment]
Ah, I didn't touch any of the Terraforged settings when I made my world. After looking at the default Terraforged settings I can see that both vanilla strongholds and better strongholds are enabled. Disabling vanilla strongholds gave me what I wanted.
