### ISSUE TITLE
Server deadlock when using Terraforged

### ISSUE THREAD

**Issue by yungnickyoung** [YUNG-GANG/YUNGs-Better-Strongholds#22]
One user has experienced deadlock in a single player world from using `/locate betterstrongholds:stronghold`.

Prior discussion can be seen in #9

**Comment by yungnickyoung** [comment]
@NillerMedDild Does the server deadlock happen for every stronghold you find, or only some?

**Comment by NielsPilgaard** [comment]
It doesn't happen every time, roughly 40% I'd say.

**Comment by yungnickyoung** [comment]
Closing as 1.16 is no longer supported.
