### ISSUE TITLE
Gobber 2 mod (Fabric) 

### ISSUE THREAD

**Issue by VHadipo** [YUNG-GANG/YUNGs-Better-Strongholds#27]
i was told that a netherite pick which has a harvest level of 4 would be able to mine the ore, but when i mine the ore nothing drops. I tried in creative world, even giving myself the nether gobber pickaxe itself. still no luck. is this a bug or am i missing something? 
(also takes very very long to mine)

**Comment by yungnickyoung** [comment]
You are in the wrong place dawg
