### ISSUE TITLE
Amethyst Geodes spawn inside stronghold

### ISSUE THREAD

**Issue by Art1xs** [YUNG-GANG/YUNGs-Better-Strongholds#33]
I noticed that other interfering structures like dungeons or mineshafts will do a nice job not clipping into the build of the stronghold itself... however its a field day for amethyst geodes. I generated a few worlds and found that the problem was consistent. If an amethyst geode wants to spawn, even if there is a stronghold there, it will.

**Comment by yungnickyoung** [comment]
At the end of the day this is just Minecraft being Minecraft - not much I can do about it
