### ISSUE TITLE
Compatibility with repurposed structures (increaseWeightLimit)

### ISSUE THREAD

**Issue by davidalb97** [YUNG-GANG/YUNGs-Better-Strongholds#41]
While using Repurposed Structures with Yung's Better Strongholds, the following warning shows up on server:

```
[main/WARN]: @ModifyConstant conflict. Skipping betterstrongholds.mixins.json:StructurePoolMixin->@ModifyConstant::betterstrongholds_increaseWeightLimit(I)I with priority 1000, already redirected by repurposed_structures.mixins.json:structures.StructurePoolMixin->@ModifyConstant::repurposedstructures_increaseWeightLimitProd(I)I with priority 1000
```
From what I understand, both mods are attempting to do the same thing, but Yung's Better Strongholds mixin is the one being disabled.
Is this mod compatible with Repurposed Structures? If so, is it safe to ignore that function?

Modlist:
*  betterstrongholds@1.17-1.1.1
*  fabric@0.40.1+1.17
*  repurposed_structures@2.3.4+1.17.1
*  yungsapi@1.17-Fabric-16

[log on pastebin](https://pastebin.com/1fUvPRRA)

[Opened the same issue on Repurposed Structures](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/145)

**Comment by TelepathicGrunt** [comment]
Yungs, you can close this. It’s just a misunderstand on how our mixins work
