### ISSUE TITLE
Dining room uses petrified oak slabs instead of normal oak slabs

### ISSUE THREAD

**Issue by Timolino456** [YUNG-GANG/YUNGs-Better-Strongholds#43]
I was wondering why I couldn't mine it with my axe lol
I guess this isn't supposed to be like that?

![2021-10-16_13 08 21](https://user-images.githubusercontent.com/38137599/137584985-657fec6f-625b-4f96-a591-d7343974b189.png)

**Comment by yungnickyoung** [comment]
now that's what I call a feature

**Comment by yungnickyoung** [comment]
Fixed in 1.18 release
