### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by TheNimbleNinja** [YUNG-GANG/YUNGs-Better-Strongholds#45]
https://gist.githubusercontent.com/natanfudge/cbd3eb2070d6ae7baa9307a1e4fa727e/raw/690ac755f9d2dbfceb5a75578718ff14654ec0fb/crash.txt crash randomly exploring the world

**Comment by yungnickyoung** [comment]
Closing as 1.16 is no longer supported. I don't believe this was ever an issue with Better Strongholds.
