### ISSUE TITLE
[Feature Request] "Min Y" setting for stronghold generation

### ISSUE THREAD

**Issue by erisdev** [YUNG-GANG/YUNGs-Better-Strongholds#46]
I'd like a setting to prevent pieces of the stronghold from generating below a certain Y value, as an inverse of `Max Y`.

Rationale: I'm making a custom dimension that represents the underside of the world, where the top half of the dimension is mostly solid rock with caves and the bottom half is mostly empty space with bits of floating rock, and i'm sticking the stronghold there. I'd like to prevent stronghold pieces from extending below, say, the halfway point, to prevent rooms just floating in the abyss.

**Comment by yungnickyoung** [comment]
Will be added in the 1.19 version of the mod, available now for Patrons and will be publicly available in a few months
