### ISSUE TITLE
Strongholds gen Broken 

### ISSUE THREAD

**Issue by ModernGamingWorld** [YUNG-GANG/YUNGs-Better-Strongholds#47]
After Adding This Mod In, it seems Strongholds are spawning are broken
![2022-02-17_00 09 12](https://user-images.githubusercontent.com/75923060/154416005-9d43efcb-ddc9-4d93-844a-613fd698540b.png)

**Comment by esotericist** [comment]
that looks a lot like quark's dungeons, rather than anything stronghold related.

**Comment by yungnickyoung** [comment]
Indeed, this is not a Better Stronghold.
