### ISSUE TITLE
Crashing when loading world

### ISSUE THREAD

**Issue by ghost** [YUNG-GANG/YUNGs-Better-Strongholds#48]
When I start the game and play a world, the world is loaded without problems first. But when I quit to title and try to play the world again, the game crashes.
Crash Report:
https://pastebin.com/AK9i9hvg

**Comment by sloweia** [comment]
same

**Comment by yungnickyoung** [comment]
Will look into this today

**Comment by yungnickyoung** [comment]
Working on a fix for this. In the meantime, you should be able to rejoin your world after restarting the game - let me know if that works for you.

**Comment by yungnickyoung** [comment]
Okay, v1.0.2 should fix this. It requires YUNG's API vForge-24, so make sure you grab that. Let me know if it works for you guys and if so I'll close this issue.

**Comment by ghost** [comment]
It worked correctly. Thank you.
