### ISSUE TITLE
[BUG] problems with generation

### ISSUE THREAD

**Issue by Polarite** [YUNG-GANG/YUNGs-Better-Strongholds#54]
I noticed when using C2Me, it would repeatedly warn me about stronghold positions initialized, c2me dev is telling me a mod(in this case your mod) asks for stronghold positions maybe, therefore slowing down chunk generation speed. Please fix if possible ^<^

**Comment by yungnickyoung** [comment]
Can you post some logs showing the warning? I'm not sure about any point in the code where it would be recalculating stronghold positions.

**Comment by Polarite** [comment]
sadly I cant send logs since I deleted the pack I was doing stuff in, but you can simply install c2me and yungs better strongholds mods and you will see the logs spammed while new chunks are generated.

**Comment by yungnickyoung** [comment]
Closing due to lack of information. Feel free to open a new issue with more information (logs, version numbers, etc) if this is still an issue.
