### ISSUE TITLE
Chunks not Loading at Better Strongholds locations.

### ISSUE THREAD

**Issue by Splurpy** [YUNG-GANG/YUNGs-Better-Strongholds#56]
Hi. First, thanks for taking the time to look at this.
I've been trying to create my own modpack to use on a private server with friends, and I knew I had to have YBS. Unfortunately, when I use /locate to find a stronghold, the coordinates it gives me always lead to an unrendered portion of the map. When I say unrendered, I mean complete void wall.

[Video Here](https://www.youtube.com/watch?v=5w1GRjMnle4)

I've tried numerous new worlds, various shader/optifine settings, and none of that fixed the issue. However, when uninstalling YBS, this didn't occur at regular strongholds, nor any other major structures I could find. I'm not sure if it's an incompatibility issue, but I thought I'd post this here in the hopes of:
1. Finding a solution/fix       OR
2. Understanding if it can't be fixed, so I don't waste time trying to make it work

I had also seen similar issues with optifine versions close to 1.16.5 (which is what I'm using), but the problem no longer persists when removing the mod altogether, so I'm not sure if that's a coincidence or not.

**Comment by yungnickyoung** [comment]
A few things:
- Reproduce the problem and then upload the latest.log here. You can use a pastebin link for this
- Try teleporting elsewhere/loading new chunks after traveling to a stronghold location to see if it's really a rendering issue, or if instead the server is hanging/not responsive
- Try removing Optifine
- Try removing all other mods except YBS to see if the problem persists. If it doesn't, then remove half of your mods at a time until you narrow it down to the other mod(s) causing the compatibility issue

**Comment by Splurpy** [comment]
> 

The file was too large for PasteBin, so I uploaded it for viewing on DropBox [here](https://www.dropbox.com/s/dlezwfxctrcfnwl/latest.log?dl=0).

In regards to trying to teleport elsewhere- I did, and it seems like the world is hanging. Nothing loads in anywhere else once I try to go to the stronghold location, and not even throwing ender pearls or eyes of ender does anything.

Thanks for your help, I'll begin the other suggestions now, as well.

**Comment by Splurpy** [comment]
> * Try removing Optifine

Just finished trying this: It seems Optifine wasn't the culprit. Exact same thing happens, exact same place.

**Comment by Splurpy** [comment]
Alright- Went through all of my mods.

For anyone with a similar issue, it stopped when I removed the Zombie Awareness mod, which is a shame.

I'll just remove it for now, not sure why that's the mod that causes issues.

**Thanks for the help @yungnickyoung **
