### ISSUE TITLE
Client Crashing on Load 1.18.1 Fabric

### ISSUE THREAD

**Issue by Gamerbolts** [YUNG-GANG/YUNGs-Better-Strongholds#57]
Hello I tried editing the config file to allow for modded ores and am getting a crash. I checked and the json file looks correct

{
  "oreChances": {
    "entries": {
      "minecraft:lapis_ore": 0.15,
      "minecraft:coal_ore": 0.2,
      "minecraft:iron_ore": 0.2,
      "minecraft:gold_ore": 0.2,
	  "minecraft:copper_ore" 0.2,
      "minecraft:emerald_ore": 0.05,
      "minecraft:diamond_ore": 0.05,
      "minecraft:redstone_ore[lit=false]": 0.15,
	  "denseores:dense_iron_ore" 0.1,
	  "denseores:dense_copper_ore" 0.1,
	  "denseores:dense_coal_ore" 0.1,
	  "denseores:dense_gold_ore" 0.1,
	  "denseores:dense_redstone_ore" 0.15,
	  "denseores:dense_lapis_ore" 0.15,
	  "denseores:dense_diamond_ore" 0.025,
	  "denseores:dense_emerald_ore" 0.025,
	  "gobber2:gobber2_ore" 0.2,
	  "byg:ametrine_ore" 0.1,
	  "byg:lignite" 0.2,
	  "byg:ametrine_ore" 0.2,
	  "byg:ametrine_ore" 0.2,
	  "ae2:quartz_ore" 0.2
    },
    "defaultBlock": "minecraft:coal_ore"
  }
}
Here is the crash log 
[crash-2022-04-15_10.05.58-client.txt](https://github.com/YUNG-GANG/YUNGs-Better-Strongholds/files/8496656/crash-2022-04-15_10.05.58-client.txt)

Are you just not able to input modded ores or did I do something wrong. Any help is appreciated. Thank you!

**Comment by yungnickyoung** [comment]
Your JSON is malformed. You are missing several colons, and possible other things. You can use https://jsonlint.com/ to see if your JSON is valid.
