### ISSUE TITLE
"Experimental settings" warning screen on a clean instance with nothing else installed

### ISSUE THREAD

**Issue by ccrowles** [YUNG-GANG/YUNGs-Better-Strongholds#59]
Same as the issues I submitted [for Better Mineshaft](https://github.com/YUNG-GANG/YUNGs-Better-Mineshafts/issues/81) and [for Better Dungeons](https://github.com/YUNG-GANG/YUNGs-Better-Dungeons/issues/34): I get the experimental settings warning on a new instance in a new world with only this mod and its api installed.

Minecraft version: 1.18.2
Forge version: 40.1.16

Logfile: [latest.log](https://github.com/YUNG-GANG/YUNGs-Better-Strongholds/files/8645174/latest.log)

PolyMC output: [here](https://0x0.st/omo2.txt)

**Comment by TelepathicGrunt** [comment]
That is normal. Any mod or datapack using mojang's json worldgen system will show the experimental screen. My mods and many others do trigger the screen too. This is vanilla behavior and can be ignored. It's just Mojang's way of warning players that the world is going to use the json worldgen system which is totally fine. 

You can use this mod to turn off the screen and not see it anymore.
https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings
