### ISSUE TITLE
No end portal in the stronghold

### ISSUE THREAD

**Issue by Schummel-8** [YUNG-GANG/YUNGs-Better-Strongholds#6]
I was searching through the whole stroghold, also in spectator with night vision and can't find the portal...
Maybe it is a generating bug

I have also some other mods installed like repurposed structures and end remastered, could there be a problem with them?

**Comment by yungnickyoung** [comment]
Tbh I suspect you just haven't found it. But if you provide the seed, I can take a look.

**Comment by Schummel-8** [comment]
nvm, found it now...
sorry for bothering you.

**Comment by yungnickyoung** [comment]
Lol no worries
