### ISSUE TITLE
Strongholds don't generate with the latest version of Terra world generation.

### ISSUE THREAD

**Issue by naughtius-maximus-8492** [YUNG-GANG/YUNGs-Better-Strongholds#61]
With the release of the latest beta of Terra 6.0 (6.0.0-BETA+b6b6cb185), strongholds don't generate within Terra. This is also true for all structures in Yung's mods.

Versions:
Minecraft 1.18.2
Fabric 0.14.6
Terra 6.0.0-BETA+b6b6cb185 (accessed via Modrinth https://modrinth.com/mod/terra/versions)
Yungs Better Strongholds 2.1.1
Yungs API 2.0.8

Steps to reproduce:

1) Create a world using Terra as the generator.
2) Run the command /locate betterstrongholds:stronghold.
3) Observe the error message "could not find a structure of type "betterstrongholds:stronghold" nearby".
4) Also try using an Eye of Ender.
5) Observe the Eye of Ender failing to deploy.

**Comment by dfsek** [comment]
This person is using an alpha version of Terra, which had an issue where Terra biomes were not being properly tagged. The Terra issue was fixed before the actual release version of 6.0; this issue can be closed.

I'm not sure why they reported an issue with a Terra alpha to you and never said anything to us, lol

**Comment by yungnickyoung** [comment]
¯\_(ツ)_/¯
