### ISSUE TITLE
How to stop stronghold spawning?

### ISSUE THREAD

**Issue by JacoalkRed** [YUNG-GANG/YUNGs-Better-Strongholds#62]
Hi,I am here to ask a question.Is that possible for you to make a datapack or fabric mod to stop spawn vanilla stronghold?

**Comment by JacoalkRed** [comment]
At the beginning ,I want to stop stronghold to spawn,but everyone told me that the stronghold is still in the config file in the config folder above the mods folder.
But I still want to ban the end portal,So can it happen to replace the end-portal block to something else to achieve the goal?
basicly I want to do it by datapack or serverside fabric mod.

**Comment by JacoalkRed** [comment]
I truly want to disable strongholds,but I dont know how to do that by datapack.Beacause i cant find the stronghold structures file.Would you plz help me to make a datapack to disable strongholds?Also i will try to do it on my own,I start learning datapack just from yesterday,So i have many things to learn!

**Comment by yungnickyoung** [comment]
Hey, this can be done via data pack depending on the version you're on. Ask for help in the Discord - there are way more people in there to help you out and you'll get a response much more quickly!
