### ISSUE TITLE
Add vanilla loot tables support for the sake of mod compatibility

### ISSUE THREAD

**Issue by yungnickyoung** [YUNG-GANG/YUNGs-Better-Strongholds#7]

**Comment by 77wisher77** [comment]
An example of a mod where this would be useful is `Quark`, which injects "Tomes" into the vanilla stronghold library rooms.
Also `Botania` which adds black lotus flowers to various chests

I'm having trouble making a datapack to add in the vanilla loot tables, which would be a possible solution, i've tried a vew variations of the following and failed to change either the grand library or library chest loot:

path: `data/betterstrongholds/loot_tables/chests/grand_library.json` and also `library.json` in the same directory|
i also tried moving the .jsons into further subdirectories titled `stronghold`, `overworld`

the contents of the jsons is:
```json
{
  "type": "minecraft:chest",
  "pools": [
    {
        "rolls": 1,
        "entries": [
            {
                "type": "minecraft:loot_table",
                "name": "minecraft:chests/stronghold_library",
                "weight": 1
            }
        ]
    }
  ]
}
```

and

```json
{
  "pools": [
      {
          "rolls": 1,
          "entries": [
              {
                  "type": "item",
                  "weight": 1,
                  "name": "minecraft:stick",
                  "functions": [
                      {
                          "function": "set_count",
                          "count": {
                              "min": 1,
                              "max": 5
                          }
                      }
                  ]
              }
          ]
      }
  ]
}
```

none of which worked, i'm sure I am missing something simple, but could I get some help with the datapack, im guessing its the directory structure where I am going wrong

But definitely a +1 for a config option for vanilla loot tables to increase mod compatability

**Comment by yungnickyoung** [comment]
This has been added starting in 1.19.
