### ISSUE TITLE
Warning sign

### ISSUE THREAD

**Issue by Psychodeus** [YUNG-GANG/YUNGs-Better-Strongholds#71]
![image](https://user-images.githubusercontent.com/93028949/199233314-2e19ff9b-6275-4d1c-bca5-488a97674e37.png)
Why after I install those mods, I got these:
![image](https://user-images.githubusercontent.com/93028949/199233396-61f71fca-ff3a-4edd-a9d2-34153ebfc8da.png)
Any way to disable it?

**Comment by ghost** [comment]
Install the mod _Here Be No Dragons!_
