### ISSUE TITLE
Help with mod integration

### ISSUE THREAD

**Issue by awesomedeity** [YUNG-GANG/YUNGs-Better-Strongholds#72]
I'm using Integrated Strongholds. I'd like to only have integrated Strongholds spawn in the overworld. However I'd like to use Better Strongholds and Repurposed Structures to spawn Better Strongholds in the nether. Is it possible to use your mod to overhaul my nether strongholds without having Better Strongholds spawning in the overworld? If it is possible how would I do such a thing?

**Comment by Boba194230** [comment]
I would also like to know this as I'm trying to use the stronghold from dungeons and taverns but keep the better strongholds for the repurposed ones.

**Comment by yungnickyoung** [comment]
I think the best way to do this is to make a data pack that overrides the list of biomes Better Strongholds can spawn in, and replace it with an empty list. So you would make a data pack that overrides this file: https://github.com/YUNG-GANG/YUNGs-Better-Strongholds/blob/1.20/Common/src/main/resources/data/betterstrongholds/tags/worldgen/biome/has_structure/better_stronghold.json
and replace it with:

```json
{
  "replace": true,
  "values": [
  ]
}
```

Btw if you have technical or compatibility questions, please ask them in the [Discord](discord.gg/yung)! I try to keep GitHub as a place solely for feature suggestions and bug reports. Gonna close this issue for that reason, but feel free to ask any further questions in the Discord.
