### ISSUE TITLE
[Enhancement] The ability to choose which dimension(s?) the strongholds can spawn in

### ISSUE THREAD

**Issue by Pikabyte** [YUNG-GANG/YUNGs-Better-Strongholds#8]
I always thought it was annoying in vanilla that there was no way for packdevs to change the default progression for getting to the end without just straight up disabling strongholds and making end portal recipes.

I really think it'd be a neat way to change up progression if you could make strongholds spawn in other dimensions, requiring you to explore those dimensions first. This allows for some neat gating and some extra flavor when combined with your Better Portals mod, for instance.

**Comment by yungnickyoung** [comment]
Added in v1.1.
