### ISSUE TITLE
Crash. Your mod was mentioned but dont know if its the direct cause.

### ISSUE THREAD

**Issue by ArrowFX** [YUNG-GANG/YUNGs-Better-Strongholds#83]
https://paste.ee/p/NeOLi

**Comment by SiverDX** [comment]
```
java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / terralith:snowy_cherry_grove]=net.minecraft.world.level.biome.Biome@2f0d47d6}, Reference{ResourceKey[minecraft:worldgen/biome / biomesoplenty:lush_savanna]=net.minecraft.world.level.biome.Biome@7b6abbc7}]
```

incompat between terralith and biomesplenty or due to some other worldgen (excluding structures) mod interaction
since you're using cyclic you can try this: https://modrinth.com/mod/cyclic-crash-fixer

**Comment by ArrowFX** [comment]
Worked like a charm! Have been playing for 3 hours now and no crash! Thanks for recommending that mod!
