### ISSUE TITLE
compatibility question

### ISSUE THREAD

**Issue by SecretiXz** [YUNG-GANG/YUNGs-Better-Strongholds#84]
does yung's structures support terralith, nullscape and amplified nether?
does new structures compatible with blaze and cave advancement pack? wont some advancements break if this mods are installed?

**Comment by yungnickyoung** [comment]
In general, yeah my mods are compatible with terralith, nullscape and amplified nether.

For the advancement pack - I don't know the exact specifics of that pack, but *typically* the onus is on the author of the pack to add support for modded structures to their advancements. I recommend maybe asking the authors of that pack if there is compatibility, or just testing yourself in a quick test world.

Btw this issue report is really meant for bug reports and whatnot, if you have compatibility questions in the future please ask in the [discord](https://discord.gg/yung)!
