### ISSUE TITLE
Weird Lag With TerraForged

### ISSUE THREAD

**Issue by ghost** [YUNG-GANG/YUNGs-Better-Strongholds#9]
throw ender eye in TerraForged World will cause freeze

Forge 36.1.4
Minecraft 1.16
Java HotSpot 8

TerraForged
BetterStrongholds 1.0.1
YungsApi Forge-6
All Mod setting :  Default

**Comment by ghost** [comment]
https://spark.lucko.me/0a9pMaPI5k

**Comment by yungnickyoung** [comment]
Thanks for the spark report. Looks like Terraforged's ChunkGenerator takes control of the locate procedure, as expected. However, once it gets to the point of structure start initialization (`func_230364_a_`) and calls my custom reimplementation of `JigsawManager$func_242837_a`, it takes _way_ longer than usual. In particular, method calls to `VoxelShapes$combine` are quite long.

I have no idea why this might change with Terraforged's chunk generator. I would make an issue report with them, and reference this issue in it.

**Comment by NielsPilgaard** [comment]
Edit: I hope this is related to this issue ^^*
I managed to deadlock my single player world using just `/locate betterstrongholds:stronghold`
Here's a snapshot taken with visualVM, hope it helps 😄 

[sample.zip](https://github.com/yungnickyoung/YUNGs-Better-Strongholds/files/6604816/sample.zip)

**Comment by yungnickyoung** [comment]
@NillerMedDild Does this occur for every stronghold you find?

**Comment by yungnickyoung** [comment]
Btw, this does seem to be a separate issue from this, so I will make an additional issue and redirect us there.

**Comment by NielsPilgaard** [comment]
@yungnickyoung Does what occur exactly? :)

**Comment by yungnickyoung** [comment]
See my post in #22 . I want to keep this issue report focused on @AIMATO's problem.

**Comment by yungnickyoung** [comment]
Closing as 1.16 is no longer supported.
